# Generated by Django 5.2.4 on 2025-11-30 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('citizenship_file', models.FileField(blank=True, help_text='Upload citizenship document file', null=True, upload_to='buyer_docs/')),
                ('nid_file', models.FileField(blank=True, help_text='Upload NID document file', null=True, upload_to='buyer_docs/')),
                ('passport_photo', models.FileField(blank=True, help_text='Upload passport size photo (required)', null=True, upload_to='buyer_docs/')),
                ('signature_image', models.FileField(blank=True, help_text='Upload signature (required)', null=True, upload_to='buyer_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Profile',
                'verbose_name_plural': 'Buyer Profiles',
            },
        ),
    ]
