# Generated by Django 5.2.4 on 2025-12-30 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmo', '0002_alter_tmoofficer_officer_id_alter_tmoofficer_user'),
        ('users', '0002_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='verification_remarks',
            field=models.TextField(blank=True, help_text='Remarks by TMO Officer during verification'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status by TMO Officer', max_length=20),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when verification was completed', null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='TMO Officer who verified this buyer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_buyers', to='tmo.tmoofficer'),
        ),
    ]
