# Generated by Django 5.2.4 on 2026-01-08 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmo', '0002_alter_tmoofficer_officer_id_alter_tmoofficer_user'),
        ('users', '0003_buyerprofile_verification_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showroom_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(help_text='Business registration number', max_length=50, unique=True)),
                ('pan_number', models.CharField(help_text='PAN number of the showroom', max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('alternative_phone', models.CharField(blank=True, max_length=15)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_citizenship', models.CharField(max_length=50)),
                ('registration_certificate', models.FileField(help_text='Business registration certificate', upload_to='showroom_docs/')),
                ('pan_certificate', models.FileField(help_text='PAN registration certificate', upload_to='showroom_docs/')),
                ('owner_citizenship_file', models.FileField(help_text="Owner's citizenship document", upload_to='showroom_docs/')),
                ('showroom_photo', models.ImageField(help_text='Photo of the showroom', upload_to='showroom_docs/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status by TMO Officer', max_length=20)),
                ('verification_remarks', models.TextField(blank=True, help_text='Remarks by TMO Officer during verification')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date and time when verification was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='TMO Officer who verified this showroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_showrooms', to='tmo.tmoofficer')),
            ],
            options={
                'verbose_name': 'Showroom Profile',
                'verbose_name_plural': 'Showroom Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('engine_number', models.CharField(max_length=50)),
                ('make', models.CharField(help_text='e.g., Toyota, Honda', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('bus', 'Bus'), ('van', 'Van')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=20)),
                ('engine_cc', models.IntegerField(help_text='Engine capacity in CC')),
                ('seating_capacity', models.IntegerField()),
                ('photo_front', models.ImageField(upload_to='vehicle_photos/')),
                ('photo_back', models.ImageField(upload_to='vehicle_photos/')),
                ('photo_left', models.ImageField(upload_to='vehicle_photos/')),
                ('photo_right', models.ImageField(upload_to='vehicle_photos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_receipt', models.FileField(help_text='Cheque or payment receipt', upload_to='payment_receipts/')),
                ('temporary_plate_number', models.CharField(blank=True, help_text='Temporary number plate', max_length=20)),
                ('permanent_plate_number', models.CharField(blank=True, help_text='Permanent number plate (assigned after verification)', max_length=20, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_remarks', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vehicles', to='users.buyerprofile')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.showroomprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vehicles', to='tmo.tmoofficer')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleOwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_owner', models.BooleanField(default=True)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_history', to='users.buyerprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='users.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Ownership History',
                'verbose_name_plural': 'Vehicle Ownership Histories',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
