# Generated by Django 5.2.4 on 2026-01-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_showroomprofile_vehicle_vehicleownershiphistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status by TMO Officer', max_length=20),
        ),
    ]
