# Generated by Django 5.2.4 on 2026-01-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_vehicle_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='permanent_plate_number',
            field=models.CharField(blank=True, help_text='Permanent number plate (assigned by TMO officer)', max_length=20, null=True, unique=True),
        ),
    ]
