# Generated by Django 5.2.4 on 2025-12-18 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TMOOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.CharField(help_text='Unique officer identification number', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(default='Vehicle Registration', help_text='Department within TMO', max_length=100)),
                ('has_changed_password', models.BooleanField(default=False, help_text='Whether officer has changed default password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tmo_officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TMO Officer',
                'verbose_name_plural': 'TMO Officers',
                'ordering': ['-created_at'],
            },
        ),
    ]
