# Generated by Django 5.2.4 on 2025-12-30 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmoofficer',
            name='officer_id',
            field=models.CharField(blank=True, help_text='Unique officer identification number', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tmoofficer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmo_officer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
