# Generated by Django 5.2.4 on 2026-02-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmo', '0002_alter_tmoofficer_officer_id_alter_tmoofficer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmoofficer',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='officer_signatures/'),
        ),
    ]
